---
- hosts: utility.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml
  tasks:
    - name: Create NFS Directories
      shell: |
        mkdir -p /VM_Export/PROD_NFS/{data,export,iso}

    - name: Set File Ownership
      shell: |
        chown -R 36:36 /VM_Export/PROD_NFS/{data,export,iso}

    - name: Set File Permissions
      shell: |
        chmod 0755 /VM_Export/PROD_NFS/{data,export,iso}

    - name: Copy Export Configuration File
      copy:
        src: ./Resources/Final_exports
        dest: /etc/exports

    - name: Export Filesystem
      shell: |
        exportfs -a
