---
- hosts: rhv-m.example.com
  user: ansible-user
  become: true
  vars_files:
    # Contains variables to connect to the Manager
    - engine_vars.yml
    # Contains encrypted engine_password variable using ansible-vault
    - passwords.yml

  pre_tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"
        ca_file: "{{ engine_cafile | default(omit) }}"
        insecure: "{{ engine_insecure | default(true) }}"
      tags:
        - always

  vars:
    data_center_name: Production
    cluster_name: Production_Cluster
    cluster_description: Production Cluster

  tasks:

    - name: Delete VM Pool
      ovirt_vmpool:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ cluster_name }}"
        name: Demo_Pool
        state: absent


  post_tasks:
    - name: Logout from RHV
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - alwaysovi
