---
- name: Install AAA packages
  yum:
    name: ovirt-engine-extension-aaa-*
    state: present

- name: Install mod_auth_gssapi
  yum:
    name: mod_auth_gssapi
    state: present
  when: aaa_sso_keytab is defined

- name: Deploy profile
  template:
    src: profile
    dest: /etc/ovirt-engine/aaa/{{ aaa_profile_name }}.properties
    owner: ovirt
    mode: 0600
  notify:
    - restart ovirt-engine

- name: Deploy normal ldap authn
  template:
    src: authn
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-authn.properties
  notify:
    - restart ovirt-engine
  when: aaa_sso_keytab is undefined

- name: Deploy http authn
  template:
    src: httpauthn
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-http-authn.properties
  notify:
    - restart ovirt-engine
  when: aaa_sso_keytab is defined

- name: Deploy http mapping
  template:
    src: mapping
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-http-mapping.properties
  notify:
    - restart ovirt-engine
  when: aaa_sso_keytab is defined

- name: Deploy authz
  template:
    src: authz
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-authz.properties
  notify:
    - restart ovirt-engine

- name: Copy keytab
  copy:
    src: "{{ aaa_sso_keytab }}"
    dest: /etc/httpd/httpd.keytab
    owner: apache
    mode: 0600
  when: aaa_sso_keytab is defined
  notify:
    - restart httpd

- name: Deploy kerberos SSO
  template:
    src: sso
    dest: /etc/ovirt-engine/aaa/ovirt-sso.conf
  when: aaa_sso_keytab is defined
  notify:
    - restart httpd

- name: Create symlink to apache configuration
  file:
    src: /etc/ovirt-engine/aaa/ovirt-sso.conf
    dest: /etc/httpd/conf.d/ovirt-sso.conf
    state: link
  when: aaa_sso_keytab is defined
  notify:
    - restart httpd

- name: Test AAA profile
  shell: /usr/bin/ovirt-engine-extensions-tool --extension-file=/etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-authn.properties --extension-file=/etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-authz.properties aaa search --extension-name={{ aaa_profile_name }}-authz
  failed_when: "0 != tool_result.rc"
  changed_when: "1 == 2"
  register: tool_result
